version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    volumes:
      - ./elastic/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana
    volumes:
      - ./elastic/kb/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.1
    container_name: filebeat
    volumes:
      - ./elastic/fb/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./app/log:/app/log
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana
    restart: always
  gogbasic:
    build:
      context: ./app
      dockerfile: basic.Dockerfile
    image: gog/basic
    container_name: gogbasic
    volumes:
      - ./app/log:/gog/log
    ports:
      - "8080:8080"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge