filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /gog/log/*.log

output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  username: elastic
  password: changeme

setup.kibana:
  host: "kibana:5601"
  username: elastic
  password: changeme

setup.dashboards.enabled: true
setup.dashboards.index: "filebeat-*"